version: '1'
services:
  server:
    build: .
    image: pizza-julia
    environment:
    - DATABASE_URL="pgsql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_TABLE}?sslmode=prefer"
    - TELEGRAM_KEY=${TELEGRAM_KEY}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_TABLE=${POSTGRES_TABLE}
    depends_on:
      - db
    links:
      - "db:database"
    restart: unless-stopped
    networks:
      - pizza_net
  db:
    image: postgres
    expose:
      - "5432"
    ports:
     - "5432:5432"
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_TABLE=${POSTGRES_TABLE}
    restart: on-failure
    networks:
    - pizza_net

networks:
  pizza_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"